docs: add missing period, correct spelling
w3c/silver pull request #526
Opened 2021-05-24 16:00 UTC by j9t

…and (automatically) remove trailing spaces

Signed-off-by: Jens Oliver Meiert <jens@meiert.com>

2021-05-27 15:07 UTC, michael-n-cooper requested changes
This seems to be mainly whitespace changes, which make it difficult to see what other changes the PR makes, and therefore to review. Generally whitespace changes should not be made as part of a PR unless it's a) critical or b) the point of the PR, as it gets hard to track history with whitespace commits in the mix.

2021-06-02 13:40 UTC, jspellman commented on explainer/index.html
> +			<li>Support a measurement and conformance structure that includes guidance for a broad range of disabilities. This includes more attention to the needs of low vision and cognitive accessibility, w
Period added

2021-06-02 13:41 UTC, jspellman commented on explainer/index.html
> +		<p>The core structure has inter-relationships with supporting documents and the scoring process. <span id="guidelines--full-structure-description"> Functional needs inform both outcomes and functio
How-To corrected

2021-06-06 17:28 UTC, jspellman commented on explainer/index.html
> +			<li>Support a measurement and conformance structure that includes guidance for a broad range of disabilities. This includes more attention to the needs of low vision and cognitive accessibility, w
Notes a new(ish?) feature in settings on the Files tab to hide white space changes.  I think we can merge this without creating a new PR.

2021-06-06 17:49 UTC, jspellman commented on explainer/index.html
> +			<li>Support a measurement and conformance structure that includes guidance for a broad range of disabilities. This includes more attention to the needs of low vision and cognitive accessibility, w
Deleting. Replaced by #533

2021-06-06 22:59 UTC, closed without merging