CORRECT OBSOLETE CODE THAT IS CAUSING PROBLEMS
w3c/silver pull request #568
Opened 2021-11-13 13:43 UTC by Myndex

Okay, in lieu of pull request  #213, this pull request addresses Jeanne's concerns and also get the bad information away from any links.

**TO BE CLEAR:** the document this pull request is correcting **was never supposed to be public facing and linked** per my understanding it was going to be replaced by the FPWD — but the correct code was deleted from the FPWD,  and in this doc was _BAD OBSOLETE CODE_ that should have been replaced is STILL LINKED, and now there are several instances of bade code in the wild as a result.

### THIS IS CAUSING PROBLEMS

For reasons that are unclear, the links to this OBSOLETE CODE keep popping and being distributed as if someone is attempting to sabotage this project.

In THIS request**, I left the code** and only made minor fixes, and mainly, added a "depreciated" banner with a link to the CURENT WCAG 3.0 working draft.

PLEASE PUSH THIS PULL REQUEST THROUGH. This supersedes the previous request (#213)

2021-11-20 04:11 UTC, Myndex commented
Also, this is now showing an error I have not seen before:

> ipr — GitHub signature does not match known secret for w3c/silver.

Is there anything I need to do to correct this? I looks like some kind of authentication problem.

Thank you

Andy

2021-11-22 17:55 UTC, jspellman requested changes
There is a new procedure for getting changes into WCAG3 documents. We have to all updates to the Editor's draft approved by AGWG.  We are doing that by putting them in branches and showing AGWG the branch for their approval.  

Please make this a PR into a new w3c branch "visual-contrast-updates_as". I have set the branch up for you in case you do not have permissions for it.  Once that is set up, we can put it on a survey to be approved by AGWG.  

The ASCII art around the Deprecated sections is inaccessible and doesn't meet W3C styles for specs.  A simple "This section has been depreciated" is acceptable.  Is there a reason you are marking it up as Depreciated instead of removing it?  It looked to me like it could be removed without harm. Am I misunderstanding?

2021-11-22 17:56 UTC, jspellman commented
@Myndex I will look into the ipr problem.  A number of people have complained about that recently, so it may be a new process or a bug.

2021-11-22 23:17 UTC, Myndex commented
> There is a new procedure for getting changes into WCAG3 documents. We have to all updates to the Editor's draft approved by AGWG. We are doing that by putting them in branches and showing AGWG the branch for their approval. Please make this a PR into a new w3c branch "visual-contrast-updates_as". I have set the branch up for you in case you do not have permissions for it. Once that is set up, we can put it on a survey to be approved by AGWG.

Ok, I will move to that branch. When survey approved that branch will be applied to main and the linked document?

> The ASCII art around the Deprecated sections is inaccessible and doesn't meet W3C styles for specs. A simple "This section has been depreciated" is acceptable. 

There is no ASCII art. The use of // is a standard method for commenting inside code blocks, which is where those are placed. This is a block of JS code.

> Is there a reason you are marking it up as Depreciated instead of removing it? It looked to me like it could be removed without harm. Am I misunderstanding?

Then I'm confused here Jeanne, as I've been asking that it be removed for over a year.

I created PR #213 over a year ago where I did indeed delete the depreciated code that never should have been public facing. That pull request is still sitting there with no action taken. In the comments of that PR, you stated that you didn't want the code to be deleted. Therefore I created this new PR leaving the code in (with corrections) but clearly identifying the depreciated materials.

The amount of damage that has been done to this project by having the incorrect code distributed in this way is difficult to estimate, but it has been a massive waste of my time and energy tracking down the developers that are using the incorrect code.

Thank you,

A

2021-11-23 09:21 UTC, patrickhlauke commented on guidelines/methods/Method-font-characteristic-contrast.html
> +<p class="breadcrumb"><a href="../../guidelines/index.html">Silver</a> > <a href="../explainers/VisualContrast.html">Visual Contrast</a> > DEPRECIATED </p>
note that the correct term is "deprecated", not "depreciated"

2021-11-23 09:23 UTC, patrickhlauke commented on guidelines/methods/Method-font-characteristic-contrast.html
> +	<h2 id="">	THIS DOCUMENT IS NOT MAINTAINED  </h2>
having a heading that heads up no subsequent content is a bit illogical. suggest choosing another way to mark this up.

2021-11-23 09:24 UTC, patrickhlauke commented on guidelines/methods/Method-font-characteristic-contrast.html
> +///////////////////////////////////////////////////////////////////////////////
not sure this sort of heavy-handed ASCII art approach is appropriate here, as it will result in an unnecessarily wordy and annoying/confusing output for screen reader users. suggest just keeping it short and simple and avoid "slash slash slash slash slash slash slash slash slash..."

2021-11-23 10:00 UTC, patrickhlauke commented on guidelines/methods/Method-font-characteristic-contrast.html
> +<div><span>    ///  DEPRECIATED  ///   ///  DEPRECIATED  ///   ///  DEPRECIATED  ///
there's probably a much more stylish/sensible way of noting this rather than uppercase text with ASCII art separators. suggest looking at how deprecation notices are implemented in other specs (using CSS-styled blocks, rather than relying on this sort of presentational text approach)

2021-11-23 12:09 UTC, Myndex commented on guidelines/methods/Method-font-characteristic-contrast.html
> +<p class="breadcrumb"><a href="../../guidelines/index.html">Silver</a> > <a href="../explainers/VisualContrast.html">Visual Contrast</a> > DEPRECIATED </p>
Ah, well my dyslexia and low vision are exposed. This being a case where I type the word once and copy/paste it, the error is replicated. And naturally I looked up the etymology, and what you might find amusing is this stack answer from 2014, assuming before it made it into dictionaries: https://stackoverflow.com/a/24472108/10315269

ALSO this is not the live pull request, #570 is (actually the original I asked for was #213 from a year ago)....

2021-11-23 12:11 UTC, Myndex commented on guidelines/methods/Method-font-characteristic-contrast.html
> +///////////////////////////////////////////////////////////////////////////////
Hi Patrick, that was identical to the original code section in that part of the doc. What was added was nothte slashes just a change of the wordage and addition of the link texts. And this is not the actual live PR, #570 is.

2021-11-23 12:30 UTC, Myndex commented on guidelines/methods/Method-font-characteristic-contrast.html
> +<div><span>    ///  DEPRECIATED  ///   ///  DEPRECIATED  ///   ///  DEPRECIATED  ///
Hi @patrickhlauke 
Again, this is not the live PR, responding to Jeanne I removed those in PR #570. Also this is a code block, so HTML/CSS inside the code block is not appropriate.

The upshot here is that **over a year ago I created PR #213 to remove this code completely** as it was only a placeholder and never intended to be something that was widely linked to the public, which is what has happened. But because the correct code was deleted from the FPWD and other confusions, some developers have been using this incorrect code **which was never intended to be a public facing canonical reference of any sort.** 

Unfortunately because of how Google has ranked this old link in searches that's what has eventually happened, creating confusion and problems for the early adopters and beta testers.

I've been trying to get this corrected for **over a year,** and my multiple requests have been completely ignored. This PR and now #570 are me "giving up" on PR #213 and trying to get at least a disclaimer warning on these pages, which people are widely linking to as if it was correct.

This directly addresses multiple issues filed here on the code repo all caused by this confusion. This has become a massive time and energy waste for me, tracing down developers who are unknowingly using and distributing the wrong code. It is almost as if someone is trying to sabotage this project.

Thank you,

Andy

2021-11-23 12:48 UTC, closed without merging

2021-11-23 12:48 UTC, Myndex commented
> I'm now lost as to what the "real" PR is versus what this PR is (if it's not a real PR, suggest closing it perhaps?)
> 
> In any case, imagine those comments, where relevant, on whatever the "real" PR is

As I said, it is #570