Editorial note cleanup june 23
w3c/silver pull request #707
Opened 2023-06-12 16:12 UTC by rachaelbradley

2023-06-15 15:52 UTC, michael-n-cooper requested changes
I left a few comments about minor fixes, good to merge after they're fixed.

2023-06-15 15:52 UTC, michael-n-cooper commented on guidelines/index.html
> +						<li><strong>Quantifiable tests:</strong> Tests where there is a high degree of consistency between test results from different testers. Examples include testing whether certain properties exist
pasto

2023-06-15 15:52 UTC, michael-n-cooper commented on guidelines/index.html
> +					<p>Equity is the outcome of processes and actions that ensure the spectrum of human reality obtains what is needed to participate, not solely access. As equity relates to WCAG it is about the im
expand PWD

2023-06-15 15:52 UTC, michael-n-cooper commented on guidelines/index.html
> +				<dd> </dd>
remove empty element

2023-06-16 15:27 UTC, jspellman approved these changes

2023-06-20 16:11 UTC, michael-n-cooper approved these changes
pushed a small change, now good to go

2023-06-21 12:25 UTC, merged