Various updates to requirements doc
w3c/silver pull request #732
Opened 2024-02-13 11:48 UTC by WilcoFiers

This PR was set up to try and address the various comments from https://github.com/w3c/silver/issues/41

2024-02-13 15:25 UTC, alastc commented on requirements/index.html
> +						<li><strong>Measurable Guidance</strong>: Certain accessibility guidance is best expressed as a pass/fail statement. Others far less so. There are needs of people with disabilities, especially
```suggestion
						<li><strong>Measurable Guidance</strong>: Certain accessibility guidance is best expressed as a pass/fail statement. Others far less so. There are needs of people with disabilities, especially cognitive and low vision disabilities, that are better captured by a different type of measurement. WCAG 3.0 can include multiple means of measurement, in addition to pass/fail statements, allowing inclusion of more accessibility guidance.</li>
```

2024-02-13 15:27 UTC, alastc commented on requirements/index.html
> +						<li><strong>Measurable Guidance</strong>: Certain accessibility guidance is best expressed as a pass/fail statement. Others far less so. There are needs of people with disabilities, especially
```suggestion
						<li><strong>Measurable Guidance</strong>: Certain accessibility guidance is best expressed as a true/false statement. Others far less so. There are needs of people with disabilities, especially cognitive and low vision disabilities, that are better captured by a different type of measurement. WCAG 3.0 can include multiple means of measurement, in addition to pass/fail statements, allowing inclusion of more accessibility guidance.</li>
```

2024-02-13 15:43 UTC, alastc commented on requirements/index.html
> +						<li><strong>Accessibility Supported</strong>: As the technologies advances, the lines between content, user agents, and assistive technology will continue to shift and blur. WCAG 3 will require
```suggestion
						<li><strong>Accessibility Supported</strong>: As the technologies advance, the lines between content, user agents, and assistive technology will continue to shift and blur. Authors should make a reasonable effort to ensure their content is accessible with the user agents and assistive technologies of their users. WCAG 3.0 can include advice to user agents and assistive technology developers.</li>
```

2024-02-20 15:24 UTC, alastc commented on requirements/index.html
> +						<li><strong>Other Scope Options</strong>: In addition to web pages conformance, WCAG 3.0 could include web sites conformance, conformance of page sections and individual components, and conform
```suggestion
						<li><strong>Scope Options</strong>: WCAG 3.0 conformance could include web pages, web sites, page sections, individual components, and conformance based on a set of tasks as defined by the author of the site or application. A task-based assessment would allow flexibility for conformance of complex applications that go beyond component/tag assessment or full-page assessment.</li>
```

2024-02-20 15:26 UTC, alastc commented on requirements/index.html
> +						<li><strong>Accessibility Supported</strong>: As the technologies advances, the lines between content, user agents, and assistive technology will continue to shift and blur. WCAG 3 will require
```suggestion
						<li><strong>Accessibility Supported</strong>: As the technologies advance, the lines between content, user agents, and assistive technology will continue to shift and blur. Interoperability may be affected by any number of factors outside of the control of the author and publisher of digital content. WCAG 3.0 can include advice to user agents and assistive technology developers. WCAG 3 does not intend to make authors responsible for interoperability problems beyond a reasonable effort.</li>
```

2024-02-20 15:29 UTC, alastc commented on requirements/index.html
> +            <p>The core guidelines are understandable by a non-technical audience. Where technical guidance is necessary, a plain language alternative of summary will be provided. Text and presentati
```suggestion
            <p>The core guidelines are understandable by a non-technical audience. Where technical guidance is necessary, a plain language alternative or summary will be provided. Text and presentation are usable and understandable through the use of plain language, structure, and design. They link to instruction videos, illustrations, and how-to where available.  Creation of new videos and illustrations are outside the scope of this project at this time.</p>
```

2024-02-20 15:30 UTC, alastc commented
Hi @WilcoFiers,

In the meeting we made some suggestions, if you're happy with those we can move it to AG review. If not, we'll catch up next time you can attend.

2024-03-24 21:01 UTC, jspellman requested changes
line 116 says "in addition pass/fail statements" but should say "true/false statements".  Ultimately, everything will resolve to pass fail, so that is not sufficiently accurate.

2024-03-26 16:05 UTC, alastc commented on requirements/index.html
> +						<li><strong>Measurable Guidance</strong>: Certain accessibility guidance is best expressed as a true/false statement. Others far less so. There are needs of people with disabilities, especially
```suggestion
						<li><strong>Measurable Guidance</strong>: Certain accessibility guidance is best expressed as a true/false statement. Others far less so. There are needs of people with disabilities, especially cognitive and low vision disabilities, that are better captured by a different type of measurement. WCAG 3.0 can include multiple means of measurement, in addition to true/false statements, allowing inclusion of more accessibility guidance.</li>
```

2024-03-27 16:56 UTC, frankie-wolf approved these changes

2024-04-02 10:30 UTC, alastc approved these changes

2024-04-02 10:31 UTC, merged